### ISSUE TITLE
Cache Busting Flask required.

### ISSUE THREAD

**Issue by amansheaven** [apoorva-dave/LicensePlateDetector-deployment-flask#1]
Since you are using a static name to store uploads and passing that name forward to detect.py methods to detect if the user go backwards and change the image it doesnt refreshes the image to the new one.
This happpens due to Browser Chache it stores the file for faster access. The way to fix this issue are as follows

1. Cache busting : it makes separate url_for dynamic calls where every file is added with a hidden hash to differentiated , this module is easily as flask extension one such module which i use is https://pypi.org/project/Flask-CacheBuster/

2. Use a Time Identifier: With the use of a specific time specifier to differentiate between files is also a solution this is a little tougher to implement but its something which would keep your uploads safe.

**Comment by apoorva-dave** [comment]
hey, thanks for your input. I understand your point and will check this. If you want to fix it yourself, please feel free to raise a pull request.
